export interface GalleryImage {
  src: string
  alt: string
  location?: string
  story?: string
  width: number
  height: number
}

export const LOCATION_COORDS: Record<string, { cx: number; cy: number; label: string }> = {
  "Alanya, Turkey": { cx: 545, cy: 195, label: "Alanya" },
  "Istanbul, Turkey": { cx: 530, cy: 182, label: "Istanbul" },
  "Amman, Jordan": { cx: 548, cy: 210, label: "Amman" },
  "New York, NY": { cx: 280, cy: 175, label: "New York" },
  "San Diego, CA": { cx: 195, cy: 195, label: "San Diego" },
  "Catalina Island, CA": { cx: 200, cy: 198, label: "Catalina" },
  "Disneyland, CA": { cx: 198, cy: 197, label: "Disneyland" },
  "Turkey": { cx: 537, cy: 190, label: "Turkey" },
}

/**
 * Gallery manifest. Add/remove/reorder images here.
 * Images live in /public/images/gallery/
 *
 * To add a story to any image, fill in the `story` field.
 * Stories appear in the Exhibition view and the 3D Gallery Walk.
 */
export const GALLERY: GalleryImage[] = [
  { src: "/images/gallery/Alanya-(6-of-20).jpg", alt: "Crystal waters in the forest", location: "Alanya, Turkey", story: "Crystal blue water hidden among a forest of green. Perfectly clear, impossibly still. Alanya keeps tucking places like this away where you least expect them. You walk through trees and suddenly the world opens up into something you didn't know existed five minutes ago.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alanya-(9-of-20).jpg", alt: "Overlooking the city", location: "Alanya, Turkey", story: "My parents wanted to explore Alanya. I wasn't sure what to expect. Then I saw this. The whole city stretched out below, turquoise water so clear it looked unreal, and that unmistakable feeling of summer settling into your bones. The kind of view that stops a conversation mid-sentence.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alanya-(10-of-20).jpg", alt: "Through the ancient gates", location: "Alanya, Turkey", story: "Through the gates, adventure waits. The Turkish Riviera holds centuries of history behind walls like these, and standing here you feel the weight of it. Travel has done that for me. It gives you a reason to step outside your routine, to be fully present. This gate is what exploring feels like to me. You walk through it and the ordinary stays behind.", width: 1500, height: 1891 },
  { src: "/images/gallery/Alanya-(12-of-20).jpg", alt: "A famished cat in Alanya", location: "Alanya, Turkey", story: "Turkey is full of cats. They're everywhere, lounging on walls and weaving through markets. But this one stopped me. Thin, worn down, watching the world pass by. Sometimes travel shows you something beautiful, and sometimes it shows you something that breaks your heart. Knowing there was nothing I could do made it worse. Life is beautiful, but it's fragile. Both things are true at the same time.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alanya-(16-of-20).jpg", alt: "Cleopatra Beach from above", location: "Alanya, Turkey", story: "From the gondola, Cleopatra Beach unfolds below. Turquoise water so inviting you could wade in for hours and forget you had anywhere to be. People scattered across the sand, some swimming, some just soaking in the sun. Maybe we don't need to do anything. Maybe being here is enough.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alanya-(18-of-20).jpg", alt: "A friendly transaction", location: "Alanya, Turkey", story: "My cousin Abdullah, caught mid-transaction buying a Nutella sandwich. He had no idea I was shooting. That's what I love about these moments. Two people, a simple exchange, nothing remarkable on the surface. But there's something beautiful about the tiny, unrehearsed interactions between strangers. The ones nobody photographs. Except this time, someone did.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alanya-(20-of-20).jpg", alt: "Ships across the water", location: "Alanya, Turkey", story: "Turquoise water stretching out with a ship crossing the horizon. People standing at the dock below, maybe waiting for their departure. Why do we have to leave? Can we not just stay? I wish it were that easy. Nothing lasts forever, but in that moment, I just stood there and took it in. I'll be back.", width: 1122, height: 2208 },
  { src: "/images/gallery/Istanbul-1.jpg", alt: "Light inside the Hagia Sophia", location: "Istanbul, Turkey", story: "The Hagia Sophia. Once a church, once a mosque, now a place where history holds its breath. What strikes me most isn't the architecture, though it's stunning. It's what this building represents. Different faiths, different centuries, all layered on top of each other. It's easy to focus on where people disagree. But this place is proof of where we intersect. The light was pouring in at just the right moment, like the building was showing off.", width: 1500, height: 1000 },
  { src: "/images/gallery/Istanbul-3.jpg", alt: "Inside a spice and tea shop", location: "Istanbul, Turkey", story: "A spice and tea shop tucked into a side street in Istanbul. Rows of color, jars of things I couldn't name, and a shopkeeper who didn't mind that I was just looking. Travel taught me to wander into every store, every stall, every open door. You never know what you'll find. Sometimes it's a souvenir. Sometimes it's a conversation. Sometimes it's just a room that smells incredible.", width: 1500, height: 1000 },
  { src: "/images/gallery/Istanbul-10.jpg", alt: "The cat who guards the Hagia Sophia", location: "Istanbul, Turkey", story: "Inside the Hagia Sophia, this cat stared me down like I owed it money. Pure attitude. Maybe it wasn't happy to see another tourist. Maybe it was just completely disinterested. I'll never know. But I'm glad I caught the moment. In a building full of history and grandeur, the most memorable thing was a cat with more confidence than anyone in the room.", width: 1500, height: 1000 },
  { src: "/images/gallery/Jordan-3.jpg", alt: "The Abdoun Bridge at night", location: "Amman, Jordan", story: "The Abdoun Bridge in Amman. I studied structural engineering, and bridges were always the thing that fascinated me most. How something holds together under all that weight. Driving across it is its own experience, but seeing it from this angle at night, with the street completely empty, was something else entirely. This is the city I've visited my whole life. It never stops surprising me.", width: 1500, height: 1000 },
  { src: "/images/gallery/Jordan-4-2.jpg", alt: "Fresh juice in Amman", location: "Amman, Jordan", story: "Sometimes you just need a glass of freshly squeezed juice. Fruits so fresh you know immediately this isn't what you get from a grocery store back home. There's something grounding about standing on a street corner in Amman, drinking something that was a whole fruit thirty seconds ago. Simple. Perfect.", width: 1500, height: 1000 },
  { src: "/images/gallery/Tomb.jpg", alt: "Walking toward the light", location: "San Diego, CA", story: "Liberty Station, San Diego. An archway framing a bright opening at the other end. It looks ancient, but the feeling is timeless. Walking toward the light, I couldn't help wondering what's on the other side. The future scares me sometimes. So many unknowns. Am I making the right choices today for a better tomorrow? All any of us can do is try our best and keep walking forward. Maybe it's treasure that waits at the end. Maybe it's just more questions. Either way, you have to keep going.", width: 1500, height: 1313 },
  { src: "/images/gallery/NewYork-2-Edit.jpg", alt: "Rainy New York night", location: "New York, NY", story: "The grit of New York is something I've always found beautiful. Rain on the streets, city lights reflecting off wet pavement, the world blurred just enough to feel like a painting. We'd just come out of a Broadway show when the sky opened up. There was a scramble for umbrellas, then we ducked into a spot where live music was playing and just existed together for a while. Old friends in a city that doesn't stop. I remember every moment of that night.", width: 1500, height: 1000 },
  { src: "/images/gallery/NewYork-3.jpg", alt: "Umbrella in the rain", location: "New York, NY", story: "Umbrella in hand, the city ours to explore. The rain wasn't going to stop us. It was a beautiful night, made better by the company. Not enough time to see everything, but maybe that was the point. Maybe we needed to slow down instead of rushing through it all. Some cities are meant to be walked slowly.", width: 1500, height: 1000 },
  { src: "/images/gallery/NewYork-9.jpg", alt: "Times Square", location: "New York, NY", story: "Times Square. Busy, fast, hectic, overwhelming, and absolutely a wonder. Coming here for the first time was eye-opening. It made me realize how large life actually is. It's easy to get lost in the day-to-day, but standing in the middle of all that noise and light, you feel how much is out there. So much that's different. So much that calls for exploration.", width: 1500, height: 1000 },
  { src: "/images/gallery/TurtleLake-1.jpg", alt: "Two girls at Turtle Lake", location: "New York, NY", story: "Two young girls at the edge of the water, completely absorbed in whatever they'd found. Maybe a turtle. Maybe just their own reflections. The sun catching the surface of the lake turned the whole scene golden. Central Park has a way of creating these perfect, quiet moments inside one of the loudest cities on earth.", width: 1500, height: 1000 },
  { src: "/images/gallery/Alacati-Bike.jpg", alt: "A motorbike in Alacati", location: "Alacati, Turkey", story: "Alacati. The moment I stepped in, I knew this place was special. A walkable town full of shops, cafes, and restaurants tucked into every corner. Motorbikes parked along cobblestone streets, each one looking like it belongs in a film. No cars allowed where it matters, just people wandering and discovering. It's on my have-to-visit-again list. The kind of place that makes you want to leave your phone in your pocket and just be there.", width: 1500, height: 1277 },
  { src: "/images/gallery/APC_0194-hdr.jpg", alt: "Oga's Cantina", location: "Disneyland, CA", story: "Oga's Cantina in Galaxy's Edge. Fresh beats, alien bartenders, and more thematic detail than you can take in on one visit. I loved getting lost in this little world for a moment, pretending like I actually belonged in the Star Wars universe. The drinks were wild. The vibes were wilder.", width: 741, height: 988 },
  { src: "/images/gallery/APC_0227-hdr.jpg", alt: "Stormtrooper on guard", location: "Disneyland, CA", story: "A stormtrooper holding guard. Standing perfectly still, somehow both intimidating and absurd at the same time. I probably shouldn't get on his bad side. Then again, I've seen their aim.", width: 1500, height: 2165 },
  { src: "/images/gallery/APC_0242-hdr.jpg", alt: "A ship in Galaxy's Edge", location: "Disneyland, CA", story: "A ship parked in Galaxy's Edge, looking like it just landed. The detail on this thing is unreal. Part of me wanted to climb inside, fire up the engines, and see what happens. Maybe next time.", width: 1500, height: 987 },
  { src: "/images/gallery/APC_0305-hdr.jpg", alt: "Rey's hologram to BB-8", location: "Disneyland, CA", story: "Rey, projected as a hologram, speaking to BB-8. This must be important. The little droid looked like it was hanging on every word. So was I, honestly. Disney makes you forget you're in a theme park.", width: 1500, height: 2000 },
  { src: "/images/gallery/APC_0314-hdr.jpg", alt: "Admiral Ackbar at the helm", location: "Disneyland, CA", story: "Admiral Ackbar, piloting a ship. Oh no. I hope this isn't... a trap. It's always a trap. But at least this time, the only danger was spending too much money at the gift shop.", width: 1352, height: 1802 },
  { src: "/images/gallery/APC_0323-hdr.jpg", alt: "Stormtroopers on patrol", location: "Disneyland, CA", story: "A squad of stormtroopers on patrol. Somehow I feel a little safer knowing they'll be blasting and missing every single shot. The Empire's finest, everybody.", width: 1500, height: 934 },
  { src: "/images/gallery/APC_0986-hdr.jpg", alt: "Droid parts in Galaxy's Edge", location: "Disneyland, CA", story: "In Galaxy's Edge there's no shortage of droid parts. Scattered on shelves, half-assembled, waiting for someone to bring them to life. The attention to detail in this place is absurd. Every bolt, every wire, every scratched panel tells a story of a universe that feels lived-in.", width: 1500, height: 1125 },
  { src: "/images/gallery/APC_1139-hdr-Enhanced.jpg", alt: "Dinner at Fortunate Son", location: "San Diego, CA", story: "Fortunate Son in San Diego. The ambiance, the lighting, the way the whole place felt like stepping into someone's very cool living room. The food was delicious, but honestly it was the atmosphere that stayed with me. Some restaurants feed you. This one set a mood.", width: 1500, height: 1280 },
  { src: "/images/gallery/APC_1383.jpg", alt: "A retro cafe in East Village", location: "San Diego, CA", story: "Downtown San Diego, East Village. I found this place with a cafe tucked inside a retro-style bar. The kind of spot that looks like it's been here for decades even if it hasn't. Neon signs, vintage furniture, and a vibe that made me want to sit down and stay a while. San Diego keeps hiding gems like this in plain sight.", width: 1500, height: 1125 },
  { src: "/images/gallery/IMG_0318.jpg", alt: "Droids for sale", location: "Disneyland, CA", story: "Galaxy's Edge. What would it take to bring one of these droids home with me? They're just sitting there, looking ready to go. I'd name mine something ridiculous and let it roll around the apartment. Disney knows exactly how to make you want things that don't exist.", width: 1500, height: 2000 },
  { src: "/images/gallery/IMG_0320.jpg", alt: "Kylo Ren's command shuttle", location: "Disneyland, CA", story: "Now that's a terrifying sight. Kylo Ren's command shuttle, ramp already lowered, like he just stepped off and could still be nearby. Galaxy's Edge has a way of making you forget you're standing in a theme park in Anaheim.", width: 1500, height: 1703 },
  { src: "/images/gallery/IMG_0324.jpg", alt: "Cargo in the loading bay", location: "Disneyland, CA", story: "Cargo crates stacked in a loading bay in Galaxy's Edge. Even the stuff you're not supposed to look at is detailed. Someone at Disney designed the wear patterns on these crates. That's the kind of obsessive storytelling I respect.", width: 1500, height: 2000 },
  { src: "/images/gallery/IMG_0727.jpg", alt: "Setting the stage downtown", location: "San Diego, CA", story: "Downtown San Diego. Someone setting a table, getting the place ready for the crowds that would soon pour in. There's something honest about the quiet before the rush. Everything placed just right, and for a brief moment, it's all in order.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_0828.jpg", alt: "Geometry at Scripps Research", location: "San Diego, CA", story: "Scripps Research Institute. Perfect geometry, with the sun hitting at exactly the right angle to make every line sing. It makes me think about the architect who designed this. What led to these decisions? Why this angle, this material, this shape? Structural engineering taught me to see buildings differently. This one I could stare at for hours.", width: 1500, height: 1035 },
  { src: "/images/gallery/IMG_1062-2.jpg", alt: "A building on the water", location: "Catalina Island, CA", story: "Catalina Island. A building sitting right on the water, like it decided to step away from the mainland and never came back. An escape from the busy world. Time to slow down and be present. Sometimes you need an island to remind you that the noise isn't mandatory.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_1188.jpg", alt: "Cotton candy sky over the harbor", location: "Catalina Island, CA", story: "Boats docked in Catalina's harbor under a cotton candy sky. Pinks and purples I couldn't have planned if I tried. The best light always happens when you're not expecting it. I just pointed the camera up and let the sky do the work.", width: 1500, height: 1205 },
  { src: "/images/gallery/IMG_2572.jpg", alt: "4am at the water", location: "Alanya, Turkey", story: "Jetlag woke me at 4am. I could have stayed in bed and stared at the ceiling, but something told me to go outside. I grabbed my camera, climbed down a set of crumbling metal stairs, and found myself standing at the water's edge. Not a soul in sight. Just waves crashing at my feet and the kind of silence you forget exists. No sounds but the sea and my own breathing. I was glad I left the house that morning. Some of the best moments happen when nobody else is awake.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_3901.jpg", alt: "Autumn in Central Park", location: "New York, NY", story: "Central Park in the fall. Leaves golden brown with tinges of green and orange, the kind of colors that only last a few weeks before they're gone. Walking through here feels like reading a novel, each path a new chapter. Whose story is this? Is it mine? Seasons carry so much meaning, and with each one, time slips forward. I just hope I'm making the most of every moment I can.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_4218.jpg", alt: "Fog over Central Park", location: "New York, NY", story: "Central Park in the fall, wrapped in fog. The water disappearing into haze, the trees fading like a watercolor painting. One of these days I need to come back and rent a rowboat. Just drift around for an hour and think about nothing. Or everything. Either way, this park makes it feel like the right place to do it.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_4222.jpg", alt: "Rowboats in the fall", location: "New York, NY", story: "The rowboats of Central Park. Dreamy, especially when the leaves are changing colors. Something about a small boat on still water surrounded by autumn makes you feel like you've stepped into a painting. The kind of scene that makes you reach for your camera before you even think about it.", width: 1500, height: 989 },
  { src: "/images/gallery/IMG_5085.jpg", alt: "Outdoor dining, reimagined", location: "New York, NY", story: "Hell's Kitchen, post-shutdown. There was a time during Covid when none of us knew what the world would look like. But people crave connection. When travel opened back up, New York had transformed. Outdoor dining everywhere, live music spilling onto sidewalks. It wasn't a shutdown. It was a reimagining. This dinner, with music at our side and strangers-turned-neighbors at the next table, felt like proof that people will always find their way back to each other.", width: 1500, height: 1357 },
  { src: "/images/gallery/IMG_5282-Enhanced.jpg", alt: "Lounging in Bryant Park", location: "New York, NY", story: "Bryant Park, just after the pandemic. People wanted out. They wanted grass under their feet and friends beside them. Every time I visit this park it's a little different, but this time felt special. People were simply lounging on the green, spending time with the people they'd missed. No agenda, no rush. Just the quiet joy of being outside together again.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5298.jpg", alt: "Bryant Park and the library", location: "New York, NY", story: "The green of Bryant Park stretching out with the library standing guard behind it. One of my favorite places in the city. Every visit it's a little different. Different people, different season, different light. But the feeling is always the same. A pocket of calm in a city that rarely slows down.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5396.jpg", alt: "Sunrise through the playground", location: "Istanbul, Turkey", story: "My sister and I had a long layover in Istanbul. Long enough that we looked at each other and said, let's not stay in the airport. We found a hotel just outside the city. The next morning I woke before sunrise, grabbed my camera, and found this playground. Empty. A single slide, golden light filtering through the trees behind it. No children, no laughter, just silence and a sunrise. It gave me a feeling I wasn't expecting. Where did our youth go? Are we too old to play? The beauty in the emptiness was almost overwhelming.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5408.jpg", alt: "The empty table at sunrise", location: "Istanbul, Turkey", story: "Same layover morning, same quiet sunrise. I found a table with chairs arranged around it. Nobody sitting. Just an empty conversation waiting to happen. The sun was peeking over the horizon, casting long shadows across the seats. Should someone be here? An empty table at sunrise makes you think. Maybe we should have just sat down for a while. Not everything needs a purpose. Sometimes the moment is the purpose.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5411-2.jpg", alt: "A pathway at dawn", location: "Istanbul, Turkey", story: "Same layover morning in Istanbul. I found this pathway winding through the grounds near the hotel. The light was just starting to come up, and everything felt still. No plan, no destination, just following wherever my feet took me.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5413-2.jpg", alt: "The green building and the boars", location: "Istanbul, Turkey", story: "Same morning, still exploring. I spotted this green building and stopped to frame it. A little ominous in the early light. Funny story: about thirty seconds after I took this shot, I saw two wild boars running in the distance. I turned right back around. Some adventures end early for good reasons.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5766-2.jpg", alt: "Still water in Central Park", location: "New York, NY", story: "Central Park. The water so still it looked like glass. There's something meditative about just standing at the edge and watching nothing happen. The city is right there, just beyond the trees, but in this moment it might as well be a thousand miles away.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_5771-2.jpg", alt: "Ducks in Central Park", location: "New York, NY", story: "Just some ducks in Central Park. Going about their day, unbothered by the millions of people living around them. Sometimes the simplest subjects make the best photographs. No story needed. Just ducks being ducks.", width: 1500, height: 976 },
  { src: "/images/gallery/IMG_5795-2.jpg", alt: "Yellow cab in the dark", location: "New York, NY", story: "A yellow taxi cutting through the dark city streets. Nothing is more New York than this. The contrast of that bright yellow against the shadows of the buildings, headlights reflecting off wet asphalt. It's iconic for a reason.", width: 1500, height: 1052 },
  { src: "/images/gallery/IMG_5797.jpg", alt: "Another yellow cab", location: "New York, NY", story: "Another taxi, another moment. New York is a film set that never stops rolling. Every cab that passes is carrying someone somewhere important. Or at least somewhere interesting.", width: 1500, height: 1052 },
  { src: "/images/gallery/IMG_5907-2.jpg", alt: "A birthday stop in New York", location: "New York, NY", story: "It was actually my birthday. My sister and I were heading somewhere when I spotted this sitting area. Maybe it belongs to a business, maybe not. Either way, something about it caught my eye and I had to snap a photo before we moved on. Birthday photos don't always need candles.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_6542.jpg", alt: "The cat with attitude", location: "Alanya, Turkey", story: "Another cat in Alanya. This one had a flair for attitude. The way it looked at me, you'd think I was the one trespassing. Cats in Turkey own every street they walk on, and they know it.", width: 1500, height: 1422 },
  { src: "/images/gallery/IMG_6739-2.jpg", alt: "Biking through Central Park", location: "New York, NY", story: "Biking in Central Park has always sounded like the perfect day to me. I haven't done it yet, but every time I visit I think about it. Just need to find the right time. Maybe the right time is whenever I stop waiting for it.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_6817.jpg", alt: "Moody Bryant Park", location: "New York, NY", story: "Bryant Park on a moody day. The kind of overcast sky that makes the greens deeper and the city feel quieter than it actually is. Sometimes the best shots come when the weather doesn't cooperate.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_7000-2.jpg", alt: "A cat and a dog in Izmir", location: "Izmir, Turkey", story: "A cat and a dog, both strays, both just chilling. Living on their own terms. The cat could barely lift its head. Too much effort. Not worth it. I've never related to an animal more.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_7017.jpg", alt: "A crow over the waters of Izmir", location: "Izmir, Turkey", story: "A crow in the distance, perched above the dark waters of Izmir. Moody, quiet, a little cinematic. The kind of frame that makes you feel like you're in someone else's film.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_7019-2.jpg", alt: "A man fishing in Izmir", location: "Izmir, Turkey", story: "Just a man fishing in Izmir. There's a peace to fishing that I've never personally experienced, but I like the idea of it. Just sit there and wait. Maybe think, maybe not. It's nice in concept. I need to be in the moment more. This guy clearly figured that out before I did.", width: 1500, height: 1000 },
  { src: "/images/gallery/IMG_7023.jpg", alt: "A cat at rest in Izmir", location: "Izmir, Turkey", story: "On the boardwalk in Izmir, this cat had claimed its spot. Lounging for hours, completely unbothered by the people walking past. No anxiety, no agenda. Just resting. Watching this cat, I thought maybe we could all use that kind of permission. Permission to stop, to not be productive for a moment, to just exist in the sun.", width: 1500, height: 1076 },
]
